# Generated by Django 3.2 on 2021-04-07 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('nacionalidad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('nacionalidad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('duracion', models.IntegerField()),
                ('sinopsis', models.TextField()),
                ('fechaestreno', models.DateTimeField()),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clasificacion')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.director')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personaje', models.TextField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.actor')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.peliculas')),
            ],
        ),
    ]
