# Generated by Django 3.2 on 2021-04-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='nacionalidad',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='clasificacion',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='clasificacion',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='nacionalidad',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='genero',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='peliculas',
            old_name='clasificacion',
            new_name='clasification',
        ),
        migrations.RenameField(
            model_name='peliculas',
            old_name='fechaestreno',
            new_name='datelaunch',
        ),
        migrations.RenameField(
            model_name='peliculas',
            old_name='duracion',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='peliculas',
            old_name='genero',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='peliculas',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='reparto',
            old_name='personaje',
            new_name='character',
        ),
        migrations.RenameField(
            model_name='reparto',
            old_name='pelicula',
            new_name='movie',
        ),
    ]
