# Generated by Django 3.2 on 2021-04-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210407_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='description',
            new_name='nationality',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='description',
            new_name='nationality',
        ),
    ]
